apiVersion: v1
kind: Service
metadata:
  name: jumpbox-loadbalancer
spec:
  selector:
    jumpbox: ubuntu
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
---    
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-jumpbox
  labels:
    jumpbox: ubuntu
spec:
  volumes:
  - name: yubikey
    secret:
      secretName: yubikey-secrets
  - name: ssh-key
    secret:
      secretName: ssh-key-secret
      defaultMode: 0600
      items:
      - key:  id_rsa
        path: id_rsa
      - key:  authorized_keys
        path: authorized_keys
  - name: entrypoint
    configMap:
      name: entrypoint
      defaultMode: 0744      
  containers:
  - name: ssh-pod
    image: dcasati/k8s-jumpbox-ubuntu
    imagePullPolicy: Always
    volumeMounts:
    - name: yubikey
      mountPath: /etc/yubikey/
      readOnly: false
    - name: entrypoint
      mountPath: /scripts      
    - name: ssh-key
      mountPath: /root/.ssh
      readOnly: false
